### PR TITLE
Add fitting repos to readme

### PR DESCRIPTION
**Pull request by amcisaac**
Updated the FF table to include fitting repos, where applicable. I linked to the specific release version in the fitting repo, so for example for Sage 2.2.0 I linked to the 2.2.0 release in the sage-2.2.0 repo. Not all FFs had fitting repos (e.g. bug fixes) and some of the older ones and release candidates were harder to find due to not having explicit tagged releases. Please let me know if anything else needs changing!

I also included the link to the force field section of our website. I noticed the github links there lead to the releases of this repository, and doesn't explicitly link to the fitting repos (though typically the fitting repo is linked in the `openff-forcefields` release notes.

I was wondering if we wanted to separate out the water models from our own force fields, to make the table a bit more readable, but don't feel strongly about it.

### CODE REVIEW

**Review by ntBre — APPROVED** [review]
This looks fine to me. I know this wasn't part of your changes, but I think the DOI column would probably look better as the rightmost column. I also think it might look better to put the repo links on top of the Filename column instead of having a separate column filled with either `repo` or `None`, but that's a fairly minor concern.

**Review by lilyminium — APPROVED** [review]
@ntBre I couldn't quite parse what you were suggesting -- was it linking the filename text in the filename column? I'd be keen to explore your suggestion since I have the same slight hesitancy that it's not the most aesthetic table, but otherwise it gets the job done, so LGTM @amcisaac!

Slight preference for splitting out the water models, as well.

**Comment by ntBre** [comment]
I was suggesting putting the new `repo` links in the filename column, not the files, which I realize upon further reflection could be pretty confusing. Here's an example of a row I was picturing anyway:

| Filename                                                                               | FF line | Release Date       | Major format changes? | DOI |
|----------------------------------------------------------------------------------------|---------|--------------------|-----------------------|-----|
| [openff-2.2.1.offxml](https://github.com/openforcefield/sage-2.2.1/releases/tag/2.2.1) | Sage    | September 11, 2024 | No                    |     |

And I was going to propose adding some text like "Where applicable, the fitting repository associated with the force field is linked in the `Filename` column." All of the rows with `Repo` values of `None` in the current table could just not have links.

But yeah, functionally this table is fine, so my approving review stands!

**Comment by amcisaac** [comment]
OK, I can definitely move the DOI column. I agree about the aesthetics of the fitting repo column, though I think it's a bit confusing to link it to the file. Happy to hear other suggestions for a nicer looking way to do it, but I'm weakly against linking in the filename

**Pull request merged**
